import { create } from "zustand";
import { persist } from "zustand/middleware";

export type Language = "English" | "हिंदी" | "ಕನ್ನಡ" | "தமிழ்" | "తెలుగు" | "বাংলা";

export const languageOptions: Language[] = ["English", "हिंदी", "ಕನ್ನಡ", "தமிழ்", "తెలుగు", "বাংলা"];

export const languageCodes: Record<Language, string> = {
  English: "en",
  हिंदी: "hi",
  ಕನ್ನಡ: "kn",
  தமிழ்: "ta",
  తెలుగు: "te",
  বাংলা: "bn",
};

interface LanguageStore {
  language: Language;
  setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageStore>()(
  persist(
    (set) => ({
      language: "English",
      setLanguage: (lang: Language) => set({ language: lang }),
    }),
    {
      name: "language-storage",
    }
  )
);

export const translations: Record<Language, Record<string, string>> = {
  English: {
    "Overview": "Overview",
    "SOS": "SOS",
    "Tracking": "Tracking",
    "Insights": "Insights",
    "Analytics": "Analytics",
    "Profile": "Profile",
    "History": "History",
    "Command": "Command",
    "Settings": "Settings",
    "Dashboard": "Dashboard",
    "Premium protection active": "Premium protection active",
    "Emergency response engaged": "Emergency response engaged",
    "REAL-TIME ANALYTICS": "REAL-TIME ANALYTICS",
    "PREMIUM COMMAND CENTER": "PREMIUM COMMAND CENTER",
    "Live Tracking": "Live Tracking",
    "Operations Command": "Operations Command",
    "System Settings": "System Settings",
    "Preferred Language": "Preferred Language",
    "Emergency Contacts": "Emergency Contacts",
    "Add Contact": "Add Contact",
    "Name": "Name",
    "Relation": "Relation",
    "Phone": "Phone",
    "Contact name": "Contact name",
    "Relation (e.g. Mother)": "Relation (e.g. Mother)",
    "Add trusted contacts for quick SOS alerts.": "Add trusted contacts for quick SOS alerts.",
    "SECURE": "SECURE",
    "ALERT": "ALERT",
    "EMERGENCY": "EMERGENCY",
    "Operational Telemetry": "Operational Telemetry",
    "Security Suites": "Security Suites",
    "Home": "Home",
    "Map": "Map",
    "Insight": "Insight",
    "Me": "Me",
    "INTEGRITY": "INTEGRITY",
    "SahayAI Guardian": "SahayAI Guardian",
    "ONLINE · MULTILINGUAL · CONTEXT-AWARE": "ONLINE · MULTILINGUAL · CONTEXT-AWARE",
    "Call 112": "Call 112",
    "Describe your emergency…": "Describe your emergency…",
    "Send SOS": "Send SOS",
    "Help is on the way.": "Help is on the way.",
    "Tap the button once to instantly send SOS.": "Tap the button once to instantly send SOS.",
    "EMERGENCY DISPATCH · TAP TO ACTIVATE": "EMERGENCY DISPATCH · TAP TO ACTIVATE",
    "TAP TO SEND": "TAP TO SEND",
    "EMERGENCY TYPE": "EMERGENCY TYPE",
    "Auto-SOS in": "Auto-SOS in",
    "if no response": "if no response",
    "Triggered after fall detected at 03:42 PM": "Triggered after fall detected at 03:42 PM",
    "I AM SAFE": "I AM SAFE",
    "SEND SOS NOW": "SEND SOS NOW",
    "EMERGENCY ACTIVE · UPLINK ESTABLISHED": "EMERGENCY ACTIVE · UPLINK ESTABLISHED",
    "Stay calm. Keep your phone with you. AI Guardian is coordinating response.": "Stay calm. Keep your phone with you. AI Guardian is coordinating response.",
    "Open AI Guardian": "Open AI Guardian",
    "View Live Map": "View Live Map",
    "RESPONSE COUNTDOWN": "RESPONSE COUNTDOWN",
    "LIVE COORDINATES": "LIVE COORDINATES",
    "AI INCIDENT REPORTER": "AI INCIDENT REPORTER",
    "Speak or record. AI does the rest.": "Speak or record. AI does the rest.",
    "Tap the mic or camera. SahayAI listens, classifies the situation and auto-notifies your guardians and the command center if it's serious.": "Tap the mic or camera. SahayAI listens, classifies the situation and auto-notifies your guardians and the command center if it's serious.",
    "Tell us what's happening": "Tell us what's happening",
    "Record situation": "Record situation",
    "ACTIVATE PROTOCOL": "ACTIVATE PROTOCOL",
    "SIMULATE": "SIMULATE",
    "SIMULATION RUNNING…": "SIMULATION RUNNING…",
  },
  हिंदी: {
    "Overview": "अवलोकन",
    "SOS": "एसओएस",
    "Tracking": "ट्रैकिंग",
    "Insights": "अंतर्दृष्टि",
    "Analytics": "विश्लेषण",
    "Profile": "प्रोफाइल",
    "History": "इतिहास",
    "Command": "कमांड",
    "Settings": "सेटिंग्स",
    "Dashboard": "डैशबोर्ड",
    "Premium protection active": "प्रीमियम सुरक्षा सक्रिय",
    "Emergency response engaged": "आपातकालीन प्रतिक्रिया सक्रिय",
    "REAL-TIME ANALYTICS": "वास्तविक समय विश्लेषण",
    "PREMIUM COMMAND CENTER": "प्रीमियम कमांड सेंटर",
    "Live Tracking": "लाइव ट्रैकिंग",
    "Operations Command": "संचालन कमांड",
    "System Settings": "सिस्टम सेटिंग्स",
    "Preferred Language": "पसंदीदा भाषा",
    "Emergency Contacts": "आपातकालीन संपर्क",
    "Add Contact": "संपर्क जोड़ें",
    "Name": "नाम",
    "Relation": "रिश्ता",
    "Phone": "फोन",
    "Contact name": "संपर्क का नाम",
    "Relation (e.g. Mother)": "रिश्ता (जैसे माता)",
    "Add trusted contacts for quick SOS alerts.": "तेज़ SOS अलर्ट के लिए विश्वसनीय संपर्क जोड़ें।",
    "INTEGRITY": "अखंडता",
    "SECURE": "सुरक्षित",
    "ALERT": "चेतावनी",
    "EMERGENCY": "आपातकाल",
    "Operational Telemetry": "परिचालन दूरसंचार",
    "Security Suites": "सुरक्षा सूट",
  },
  ಕನ್ನಡ: {
    "Overview": "ಅವಲೋಕನ",
    "SOS": "ಎಸ್‌ಓ‌ಎಸ್",
    "Tracking": "ಟ್ರ್ಯಾಕಿಂಗ್",
    "Insights": "ಒಳನೋಟಗಳು",
    "Analytics": "ವಿಶ್ಲೇಷಣೆ",
    "Profile": "ಪ್ರೊಫೈಲ್",
    "History": "ಇತಿಹಾಸ",
    "Command": "ಆದೇಶ",
    "Settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "Premium protection active": "ಪ್ರೀಮಿಯಂ ಸುರಕ್ಷೆ ಸಕ್ರಿಯ",
    "Emergency response engaged": "ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ ಸಕ್ರಿಯ",
    "REAL-TIME ANALYTICS": "ರಿಯಲ್-ಟೈಮ್ ವಿಶ್ಲೇಷಣೆ",
    "PREMIUM COMMAND CENTER": "ಪ್ರೀಮಿಯಂ ಕಮಾಂಡ್ ಸೆಂಟರ್",
    "Live Tracking": "ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್",
    "Operations Command": "ಕಾರ್ಯಕ್ರಮ ಆದೇಶ",
    "System Settings": "ಸಿಸ್ಟಮ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "Preferred Language": "ಆದ್ಯತೆ ಭಾಷೆ",
    "Emergency Contacts": "ತುರ್ತು ಸಂಪರ್ಕಗಳು",
    "Add Contact": "ಸಂಪರ್ಕ ಸೇರಿಸಿ",
    "Name": "ಹೆಸರು",
    "Relation": "ಸಂಬಂಧ",
    "Phone": "ಫೋನ್",
    "Contact name": "ಸಂಪರ್ಕ ಹೆಸರು",
    "Relation (e.g. Mother)": "ಸಂಬಂಧ (ಉದಾ. ತಾಯಿ)",
    "Add trusted contacts for quick SOS alerts.": "ತ್ವರಿತ SOS ಎಚ್ಚರಿಕೆಗಳಿಗೆ ನಂಬಿಕೆಯ ಸಂಪರ್ಕಗಳನ್ನು ಸೇರಿಸಿ।",
    "INTEGRITY": "ಅಖಂಡತೆ",
    "SECURE": "ಸುರಕ್ಷಿತ",
    "ALERT": "ಎಚ್ಚರಿಕೆ",
    "EMERGENCY": "ತುರ್ತು",
    "Operational Telemetry": "ಕಾರ್ಯಾಚರಣೆ ದೂರಸಂವಹನ",
    "Security Suites": "ಸುರಕ್ಷೆ ಸೂಟ್‌ಗಳು",
  },
  தமிழ்: {
    "Overview": "கண்ணோட்டம்",
    "SOS": "எசओஎस்",
    "Tracking": "கண்காணிப்பு",
    "Insights": "நுண்ணறிவு",
    "Analytics": "பகுப்பாய்வு",
    "Profile": "சுயவிவரம்",
    "History": "வரலாறு",
    "Command": "கட்டளை",
    "Settings": "அமைப்புகள்",
    "Dashboard": "இணையவரிசை",
    "Premium protection active": "பிரீமியம் பாதுகாப்பு செயல்படுகிறது",
    "Emergency response engaged": "அவசரகால பதிலளிப்பு இயக்கப்பட்டுள்ளது",
    "REAL-TIME ANALYTICS": "நிகழ்நேர பகுப்பாய்வு",
    "PREMIUM COMMAND CENTER": "பிரீமியம் கட்டளை மையம்",
    "Live Tracking": "நேரலை கண்காணிப்பு",
    "Operations Command": "செயல்பாடுகள் கட்டளை",
    "System Settings": "கணினி அமைப்புகள்",
    "Preferred Language": "விருப்பமான மொழி",
    "Emergency Contacts": "அவசரகால தொடர்புகள்",
    "Add Contact": "தொடர்பு சேர்க்கவும்",
    "Name": "பெயர்",
    "Relation": "உறவு",
    "Phone": "ஃபோன்",
    "Contact name": "தொடர்பு பெயர்",
    "Relation (e.g. Mother)": "உறவு (எ.கா. அம்மா)",
    "Add trusted contacts for quick SOS alerts.": "விரைவான எசओஎஸ் எச்சரிக்கைகளுக்கு நம்பகமான தொடர்புகளைச் சேர்க்கவும்.",
    "INTEGRITY": "நேமையობை",
    "SECURE": "பாதுகாப்பு",
    "ALERT": "எச்சரிக்கை",
    "EMERGENCY": "அவசரம்",
    "Operational Telemetry": "செயல்பாட்டு தொலைதூரவியல்",
    "Security Suites": "பாதுகாப்பு தொகுப்புகள்",
  },
  తెలుగు: {
    "Overview": "అవలోకనం",
    "SOS": "ఎస్ఓఎస్",
    "Tracking": "ట్రాకింగ్",
    "Insights": "అంతర్దృష్టి",
    "Analytics": "విశ్లేషణ",
    "Profile": "ప్రొఫైల్",
    "History": "చరిత్ర",
    "Command": "ఆదేశ",
    "Settings": "సెట్టింగ్‌లు",
    "Dashboard": "డ్యాશ్‌బోర్డ్",
    "Premium protection active": "ప్రీమియం రక్షణ సక్రియం",
    "Emergency response engaged": "అత్యవసర ప్రతిస్పందన నిযুక్తమైంది",
    "REAL-TIME ANALYTICS": "రియల్-టైమ్ విశ్లేషణ",
    "PREMIUM COMMAND CENTER": "ప్రీమియం కమాండ్ సెంటర్",
    "Live Tracking": "లైవ్ ట్రాకింగ్",
    "Operations Command": "కార్యకలాపాల కమాండ్",
    "System Settings": "సిస్టమ్ సెట్టింగ్‌లు",
    "Preferred Language": "ఇష్టమైన భాష",
    "Emergency Contacts": "అత్యవసర సంప్రదాయాలు",
    "Add Contact": "సంప్రదాయం జోడించండి",
    "Name": "పేరు",
    "Relation": "సంబంధం",
    "Phone": "ఫోన్",
    "Contact name": "సంప్రదాయ పేరు",
    "Relation (e.g. Mother)": "సంబంధం (ఉదా. తల్లి)",
    "Add trusted contacts for quick SOS alerts.": "శీఘ్ర SOS హెచ్చరికల కోసం విశ్వస్త సంప్రదాయాలను జోడించండి.",
    "INTEGRITY": "సమగ్రత",
    "SECURE": "సురక్షితం",
    "ALERT": "హెచ్చరిక",
    "EMERGENCY": "అత్యవసరం",
    "Operational Telemetry": "కార్యకలాపాల దూరసంచారం",
    "Security Suites": "నిరాপత్తా సూట్‌లు",
  },
  বাংলা: {
    "Overview": "সংক্ষিপ্ত বিবরণ",
    "SOS": "এসওএস",
    "Tracking": "ট্র্যাকিং",
    "Insights": "অন্তর্দৃষ্টি",
    "Analytics": "বিশ্লেষণ",
    "Profile": "প্রোফাইল",
    "History": "ইতিহাস",
    "Command": "কমান্ড",
    "Settings": "সেটিংস",
    "Dashboard": "ড্যাশবোর্ড",
    "Premium protection active": "প্রিমিয়াম সুরক্ষা সক্রিয়",
    "Emergency response engaged": "জরুরি প্রতিক্রিয়া সক্রিয়",
    "REAL-TIME ANALYTICS": "রিয়েল-টাইম বিশ্লেষণ",
    "PREMIUM COMMAND CENTER": "প্রিমিয়াম কমান্ড সেন্টার",
    "Live Tracking": "লাইভ ট্র্যাকিং",
    "Operations Command": "অপারেশন কমান্ড",
    "System Settings": "সিস্টেম সেটিংস",
    "Preferred Language": "পছন্দের ভাষা",
    "Emergency Contacts": "জরুরি যোগাযোগ",
    "Add Contact": "যোগাযোগ যোগ করুন",
    "Name": "নাম",
    "Relation": "সম্পর্ক",
    "Phone": "ফোন",
    "Contact name": "যোগাযোগের নাম",
    "Relation (e.g. Mother)": "সম্পর্ক (যেমন মা)",
    "Add trusted contacts for quick SOS alerts.": "দ্রুত এসওএস সতর্কতার জন্য বিশ্বস্ত যোগাযোগ যোগ করুন।",
    "INTEGRITY": "সততা",
    "SECURE": "সুরক্ষিত",
    "ALERT": "সতর্কতা",
    "EMERGENCY": "জরুরি",
    "Operational Telemetry": "অপারেশনাল টেলিমেট্রি",
    "Security Suites": "নিরাপত্তা স্যুট",
  },
};

export const t = (key: string, language: Language): string => {
  return translations[language]?.[key] || key;
};

const reverseLookup = new Map<string, string>();
Object.values(translations).forEach((dict) => {
  Object.entries(dict).forEach(([key, value]) => {
    reverseLookup.set(value, key);
    reverseLookup.set(key, key);
  });
});

export const translateTextNode = (text: string, language: Language): string => {
  const trimmed = text.trim();
  if (!trimmed) return text;
  const key = reverseLookup.get(trimmed) || trimmed;
  const translated = t(key, language);
  return text.replace(trimmed, translated);
};
